### ISSUE TITLE
Seeing some weird output in snippet

### ISSUE THREAD

**Issue by zeke** [JasonEtco/ci-reporter#23]
Check out https://github.com/electron/electron-apps/pull/518#issuecomment-367377800

It's got some stuff like `�[92m �[0m�[32m 10180 passing�[0m�[90m (2s)�[0m` in it.

One the bright side, this person was able to fix the issues on their own and get the build passing without intervention from our team! 💯

**Comment by j-f1** [comment]
Those are ANSI colors. Something like [`strip-ansi`](https://www.npmjs.com/package/strip-ansi) should take care of them.

**Comment by JasonEtco** [comment]
Totally missed this because apparently I'm not watching this repo (🤔) but I literally just added this in #24 😆 Thanks for the report 💖

**Comment by zeke** [comment]
🤘
