### ISSUE TITLE
No CI reporter output on a PR

### ISSUE THREAD

**Issue by zeke** [JasonEtco/ci-reporter#27]
CI failed on this PR, but the reporter didn't comment on it: https://github.com/electron/electron-apps/pull/528

Not a big deal. Just wanted to report it in case it's useful for debugging.

**Comment by JasonEtco** [comment]
Thanks for the report! From my cursory look over the Travis logs for that PR, I see no reason that ci-reporter _wouldn't_ have acted. Will look into it, thanks 👍
