### ISSUE TITLE
Strip control codes

### ISSUE THREAD

**Issue by bkeepers** [JasonEtco/ci-reporter#28]
For test suites that use colorized output, comment on GitHub is a little painful on the eyes (e.g. https://github.com/probot/probot/pull/441#issuecomment-368015651).

It'd be nice if control codes we're automatically stripped: https://www.npmjs.com/package/strip-ansi

**Comment by JasonEtco** [comment]
Already fixed in #24 (3 days ago, vs your above comment 5 days ago) 😎
