### ISSUE TITLE
Do nothing in private repos

### ISSUE THREAD

**Issue by JasonEtco** [JasonEtco/ci-reporter#4]
Because of CI permissions, if the repo is private then the **ci-reporter** won't be able to access the service's APIs for the builds. There should be a check in the status event handler to prevent acting on a private repo, which would incur errors.

**Comment by j-f1** [comment]
You could ask the user to run `travis token --pro` and give the app the result.

**Comment by JasonEtco** [comment]
Yep! But then I'll need to keep track of the tokens, which means I'll likely need a database to store them, and that's more than I want to do right now. I may have to anyway, CircleCI may always need a token, but if I can avoid a database that'd be nice.

**Comment by JasonEtco** [comment]
Closing in favor of #35
