### ISSUE TITLE
Please support bitrise

### ISSUE THREAD

**Issue by itchingpixels** [JasonEtco/ci-reporter#45]
:)

**Comment by JasonEtco** [comment]
Thanks for opening @itchingpixels.

Judging by [the Bitrise docs](https://devcenter.bitrise.io), they don't have an API for requesting logs, so supporting Bitrise isn't doable right now. I do see that they have a larger API, but [its a WIP](https://devcenter.bitrise.io/api/v0.1/) so I'm hesitant to build support for something that is likely to change a lot.

If you'd like to build that support in a PR, I'm not opposed to it. We'd just have to denote that it is experimental functionality.

**Comment by JasonEtco** [comment]
Closing this until Bitrise has a usable API. @itchingpixels if you want to build this support I'm happy to review a PR.
